services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - sqout-net
  backend:
    build: ./backend
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
    ports:
      - 8080:8080
    networks:
      - sqout-net
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    # volumes:
    #   - ./client:/src
    depends_on:
      - backend
    environment:
      - PORT=5000
      - TZ=Europe/Lisbon
      - BACKEND_URL=http://backend:8080
    networks:
      - sqout-net
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - sqout-net
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource

networks:
  sqout-net:
    driver: bridge
