FROM golang:1.22.1

WORKDIR /sqout

COPY . .

RUN go get -u github.com/swaggo/swag/cmd/swag

# Install swag
RUN go install github.com/swaggo/swag/cmd/swag

RUN swag init

RUN go build -o /sqout/sqout

CMD ["/sqout/sqout"]
