# Ping Tool Configuration YAML

git-info:
  repo-link: "null" # Provavelmente desnecessário, visto que o ping está em todos os OSs
  branch: "main"
  commit: "latest"
  dev: false

exe:
  command-name: "ping"
  flags:
    ## The "count" option specifies the number of pings to send.
    - name: "count"
      type: "string"
      value: "-c"
    # The "timeout" option specifies the maximum time to wait for a response, in seconds.
    - name: "count-value"
      type: "integer"
      value: 5 
    # The "destination" option specifies the destination address to ping.
    - name: "destination"
      type: "string"
      value: "localhost"
    