// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/modules": {
            "get": {
                "description": "get JSON of all the modules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "GET all the modules in the database",
                "responses": {
                    "200": {
                        "description": "array of modules",
                        "schema": {
                            "type": "example"
                        }
                    }
                }
            }
        },
        "/modules/{module_name}": {
            "get": {
                "description": "get JSON of the module",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "GET specific module in the database",
                "responses": {
                    "200": {
                        "description": "module",
                        "schema": {
                            "type": "example"
                        }
                    }
                }
            }
        },
        "/probes": {
            "post": {
                "description": "Run the probe",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "probes"
                ],
                "summary": "POST a new probe on the database",
                "responses": {
                    "200": {
                        "description": "probe",
                        "schema": {
                            "type": "example"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "sqout",
	Description:      "sqout a modular application, implement every metric you want",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
